Добавил Recycler и немного иерархии в проект.
ArtemShendelyar/InnowisePokemons pull request #3
Opened 2024-06-24 10:02 UTC by ArtemShendelyar

Я всё сделал правильно? Или стоило сразу из Dev подтянуть изменения через Pull? Что-то я сейчас только подумал и понял, что всё же стоило через Pull...
<img src="https://github.com/ArtemShendelyar/InnowisePokemons/assets/172491829/98164dc2-77a8-4368-a1ac-c497d5b054a1" >
<img src="https://github.com/ArtemShendelyar/InnowisePokemons/assets/172491829/14f605ca-2b16-4ee1-9a5e-3178bf4653d5" width="200" height="450"> <img src="https://github.com/ArtemShendelyar/InnowisePokemons/assets/172491829/5cf1c192-c55b-4d41-b957-441b8476382c" width="200" height="450">

2024-06-24 10:32 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/innowisepokemons/recyler/PokemonDiffUtilCallback.kt
> +        items[oldItemPosition].name == newItems[newItemPosition].name
Может всё таки id ? Имя в теории может поменяться)

2024-06-24 10:33 UTC, pzinkevich42innowise commented on app/src/main/res/layout/pokemon_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Для чего нужен этот лайнир?

2024-06-24 10:34 UTC, pzinkevich42innowise requested changes
Мини-вопросики есть

2024-06-24 11:24 UTC, ArtemShendelyar commented
> Мини-вопросики есть

Да-да?

2024-06-24 11:32 UTC, ArtemShendelyar commented on app/src/main/res/layout/pokemon_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Да что-то сглупил. Заменил его на FrameLayout. 
![изображение](https://github.com/ArtemShendelyar/InnowisePokemons/assets/172491829/39fff7d1-9cb8-4ad0-9bf0-d37fcb662532)

2024-06-24 11:32 UTC, ArtemShendelyar commented on app/src/main/java/com/example/innowisepokemons/recyler/PokemonDiffUtilCallback.kt
> +        items[oldItemPosition].name == newItems[newItemPosition].name
И правда... Рано или поздно могут совпасть имена.

2024-06-24 13:21 UTC, pzinkevich42innowise commented on app/src/main/res/layout/pokemon_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
А TextView почему не может быть рутом?

2024-06-24 13:26 UTC, RaShCat commented on app/src/main/res/layout/pokemon_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Хм, а зачем он тогда вообще нужен FrameLayout...

2024-06-24 13:26 UTC, ArtemShendelyar commented on app/src/main/res/layout/pokemon_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Хм, а зачем тогда нужен FrameLayout...

2024-06-30 21:28 UTC, pzinkevich42innowise approved these changes

2024-06-30 22:10 UTC, merged